apiVersion: apps/v1
kind: Deployment
metadata:
  name: sahu-deployement
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 2
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: nikhildocker28/test1
        ports:
        - containerPort: 80
